var searchData=
[
  ['failed_5fto_5fconverge_0',['FAILED_TO_CONVERGE',['../namespacedftefe_1_1linearAlgebra.html#a0fcb8070705d90a778cc4034233c8e17add8d38f9645bb27102c8bbfd6691a7d3',1,'dftefe::linearAlgebra']]],
  ['failure_1',['FAILURE',['../namespacedftefe_1_1linearAlgebra.html#a7f110f3acb6ba66aa42477025f96586da36fc6065a3e970bc3e6b2e59da52bf2a',1,'dftefe::linearAlgebra']]],
  ['febasisdatastorage_2',['FEBasisDataStorage',['../classdftefe_1_1basis_1_1FEBasisDataStorage.html',1,'dftefe::basis']]],
  ['febasisdatastorage_2eh_3',['FEBasisDataStorage.h',['../FEBasisDataStorage_8h.html',1,'']]],
  ['febasisdatastoragedealii_4',['FEBasisDataStorageDealii',['../classdftefe_1_1basis_1_1FEBasisDataStorageDealii.html',1,'dftefe::basis::FEBasisDataStorageDealii&lt; ValueTypeBasisData, memorySpace, dim &gt;'],['../classdftefe_1_1basis_1_1FEBasisDataStorageDealii.html#aaca12ca5fc81bf39ba8cbaaa00477a29',1,'dftefe::basis::FEBasisDataStorageDealii::FEBasisDataStorageDealii()']]],
  ['febasisdatastoragedealii_2ecpp_5',['FEBasisDataStorageDealii.cpp',['../FEBasisDataStorageDealii_8cpp.html',1,'']]],
  ['febasisdatastoragedealii_2eh_6',['FEBasisDataStorageDealii.h',['../FEBasisDataStorageDealii_8h.html',1,'']]],
  ['febasisdatastoragedealii_2et_2ecpp_7',['FEBasisDataStorageDealii.t.cpp',['../FEBasisDataStorageDealii_8t_8cpp.html',1,'']]],
  ['febasishandler_8',['FEBasisHandler',['../classdftefe_1_1basis_1_1FEBasisHandler.html',1,'dftefe::basis']]],
  ['febasishandler_2eh_9',['FEBasisHandler.h',['../FEBasisHandler_8h.html',1,'']]],
  ['febasishandlerdealii_10',['FEBasisHandlerDealii',['../classdftefe_1_1basis_1_1FEBasisHandlerDealii.html',1,'dftefe::basis::FEBasisHandlerDealii&lt; ValueTypeBasisCoeff, memorySpace, dim &gt;'],['../classdftefe_1_1basis_1_1FEBasisHandlerDealii.html#a18ff3a6f0883bcb323f145272a2d83e1',1,'dftefe::basis::FEBasisHandlerDealii::FEBasisHandlerDealii(std::shared_ptr&lt; const BasisManager &gt; basisManager, std::map&lt; std::string, std::shared_ptr&lt; const Constraints&lt; ValueTypeBasisCoeff, memorySpace &gt; &gt; &gt; constraintsMap)'],['../classdftefe_1_1basis_1_1FEBasisHandlerDealii.html#aaf032f34fa86f16399693c85dfa0ff3f',1,'dftefe::basis::FEBasisHandlerDealii::FEBasisHandlerDealii(std::shared_ptr&lt; const BasisManager &gt; basisManager, std::map&lt; std::string, std::shared_ptr&lt; const Constraints&lt; ValueTypeBasisCoeff, memorySpace &gt; &gt; &gt; constraintsMap, const utils::mpi::MPIComm &amp;mpiComm)']]],
  ['febasishandlerdealii_2ecpp_11',['FEBasisHandlerDealii.cpp',['../FEBasisHandlerDealii_8cpp.html',1,'']]],
  ['febasishandlerdealii_2eh_12',['FEBasisHandlerDealii.h',['../FEBasisHandlerDealii_8h.html',1,'']]],
  ['febasishandlerdealii_2et_2ecpp_13',['FEBasisHandlerDealii.t.cpp',['../FEBasisHandlerDealii_8t_8cpp.html',1,'']]],
  ['febasismanager_14',['FEBasisManager',['../classdftefe_1_1basis_1_1FEBasisManager.html',1,'dftefe::basis']]],
  ['febasismanager_2eh_15',['FEBasisManager.h',['../FEBasisManager_8h.html',1,'']]],
  ['febasismanagerdealii_16',['FEBasisManagerDealii',['../classdftefe_1_1basis_1_1FEBasisManagerDealii.html',1,'dftefe::basis::FEBasisManagerDealii&lt; dim &gt;'],['../classdftefe_1_1basis_1_1FEBasisManagerDealii.html#a10bba2d204c3ee6860bb258c72b3a509',1,'dftefe::basis::FEBasisManagerDealii::FEBasisManagerDealii()']]],
  ['febasismanagerdealii_2eh_17',['FEBasisManagerDealii.h',['../FEBasisManagerDealii_8h.html',1,'']]],
  ['febasismanagerdealii_2et_2ecpp_18',['FEBasisManagerDealii.t.cpp',['../FEBasisManagerDealii_8t_8cpp.html',1,'']]],
  ['febasisoperations_19',['FEBasisOperations',['../classdftefe_1_1basis_1_1FEBasisOperations.html',1,'dftefe::basis::FEBasisOperations&lt; ValueTypeBasisCoeff, ValueTypeBasisData, memorySpace, dim &gt;'],['../classdftefe_1_1basis_1_1FEBasisOperations.html#a24afd20b91cbdc97278549136a06d88a',1,'dftefe::basis::FEBasisOperations::FEBasisOperations()']]],
  ['febasisoperations_2eh_20',['FEBasisOperations.h',['../FEBasisOperations_8h.html',1,'']]],
  ['febasisoperations_2et_2ecpp_21',['FEBasisOperations.t.cpp',['../FEBasisOperations_8t_8cpp.html',1,'']]],
  ['fecellbase_22',['FECellBase',['../classdftefe_1_1basis_1_1FECellBase.html',1,'dftefe::basis']]],
  ['fecellbase_2eh_23',['FECellBase.h',['../FECellBase_8h.html',1,'']]],
  ['fecelldealii_24',['FECellDealii',['../classdftefe_1_1basis_1_1FECellDealii.html',1,'dftefe::basis::FECellDealii&lt; dim &gt;'],['../classdftefe_1_1basis_1_1FECellDealii.html#a28ed619d99452cbb02f46fb93b10dc04',1,'dftefe::basis::FECellDealii::FECellDealii()']]],
  ['fecelldealii_2eh_25',['FECellDealii.h',['../FECellDealii_8h.html',1,'']]],
  ['fecelldealii_2et_2ecpp_26',['FECellDealii.t.cpp',['../FECellDealii_8t_8cpp.html',1,'']]],
  ['fecelliterator_27',['FECellIterator',['../classdftefe_1_1basis_1_1FEBasisManagerDealii.html#a78cd009c6967ce2f639a4abda84022cd',1,'dftefe::basis::FEBasisManagerDealii::FECellIterator()'],['../classdftefe_1_1basis_1_1FEBasisManager.html#aeccb3cef863e83646c223bd50cb31ad2',1,'dftefe::basis::FEBasisManager::FECellIterator()']]],
  ['fecellwisedataoperations_28',['FECellWiseDataOperations',['../classdftefe_1_1basis_1_1FECellWiseDataOperations.html',1,'dftefe::basis']]],
  ['fecellwisedataoperations_2eh_29',['FECellWiseDataOperations.h',['../FECellWiseDataOperations_8h.html',1,'']]],
  ['fecellwisedataoperations_2et_2ecpp_30',['FECellWiseDataOperations.t.cpp',['../FECellWiseDataOperations_8t_8cpp.html',1,'']]],
  ['feconstraintsbase_31',['FEConstraintsBase',['../classdftefe_1_1basis_1_1FEConstraintsBase.html',1,'dftefe::basis']]],
  ['feconstraintsbase_2ecpp_32',['FEConstraintsBase.cpp',['../FEConstraintsBase_8cpp.html',1,'']]],
  ['feconstraintsbase_2eh_33',['FEConstraintsBase.h',['../FEConstraintsBase_8h.html',1,'']]],
  ['feconstraintsdealii_34',['FEConstraintsDealii',['../classdftefe_1_1basis_1_1FEConstraintsDealii.html',1,'dftefe::basis::FEConstraintsDealii&lt; ValueTypeBasisCoeff, memorySpace, dim &gt;'],['../classdftefe_1_1basis_1_1FEConstraintsDealii.html#a599ccd8f66a7f8d3054c6dbd6f93c4a5',1,'dftefe::basis::FEConstraintsDealii::FEConstraintsDealii()']]],
  ['feconstraintsdealii_2ecpp_35',['FEConstraintsDealii.cpp',['../FEConstraintsDealii_8cpp.html',1,'']]],
  ['feconstraintsdealii_2eh_36',['FEConstraintsDealii.h',['../FEConstraintsDealii_8h.html',1,'']]],
  ['feconstraintsdealii_2et_2ecpp_37',['FEConstraintsDealii.t.cpp',['../FEConstraintsDealii_8t_8cpp.html',1,'']]],
  ['field_38',['Field',['../classdftefe_1_1basis_1_1Field.html',1,'dftefe::basis::Field&lt; ValueTypeBasisCoeff, memorySpace &gt;'],['../classdftefe_1_1basis_1_1Field.html#a914183e8c04e6ce964024ff671eef598',1,'dftefe::basis::Field::Field()']]],
  ['field_2eh_39',['Field.h',['../Field_8h.html',1,'']]],
  ['field_2et_2ecpp_40',['Field.t.cpp',['../Field_8t_8cpp.html',1,'']]],
  ['finalizetriangulationconstruction_41',['finalizeTriangulationConstruction',['../classdftefe_1_1basis_1_1TriangulationBase.html#a7cc2f19687ff25e72bc990cbee8064d8',1,'dftefe::basis::TriangulationBase::finalizeTriangulationConstruction()'],['../classdftefe_1_1basis_1_1TriangulationDealiiParallel.html#aa9b2e5631fe444f1a81e280590320677',1,'dftefe::basis::TriangulationDealiiParallel::finalizeTriangulationConstruction()'],['../classdftefe_1_1basis_1_1TriangulationDealiiSerial.html#a6e9b49731263292ef458acd09543113d',1,'dftefe::basis::TriangulationDealiiSerial::finalizeTriangulationConstruction()']]],
  ['finish_42',['finish',['../classdftefe_1_1utils_1_1mpi_1_1MPIRequestersNBX.html#ac211b9a3758cc06a9e8fe7c013ad429a',1,'dftefe::utils::mpi::MPIRequestersNBX']]],
  ['function_43',['Function',['../classdftefe_1_1utils_1_1Function.html',1,'dftefe::utils']]],
  ['function_2ecpp_44',['Function.cpp',['../Function_8cpp.html',1,'']]],
  ['function_2eh_45',['Function.h',['../Function_8h.html',1,'']]]
];
