var searchData=
[
  ['quadraturepointattributes_0',['QuadraturePointAttributes',['../classdftefe_1_1quadrature_1_1QuadraturePointAttributes.html#a52feb8d660089249d1dc9818fd9890e1',1,'dftefe::quadrature::QuadraturePointAttributes::QuadraturePointAttributes()'],['../classdftefe_1_1quadrature_1_1QuadraturePointAttributes.html#a3b74b7ca737c6b47ce4ded7e7fc3c57a',1,'dftefe::quadrature::QuadraturePointAttributes::QuadraturePointAttributes(const size_type inputCellId, const QuadratureRuleAttributes *inputQuadratureRuleAttributesPtr, const size_type inputQuadPointId)']]],
  ['quadraturerule_1',['QuadratureRule',['../classdftefe_1_1quadrature_1_1QuadratureRule.html#a1f32412137441804b2887b78983da4ea',1,'dftefe::quadrature::QuadratureRule::QuadratureRule(const size_type dim, const std::vector&lt; utils::Point &gt; &amp;points, const std::vector&lt; double &gt; &amp;weights)'],['../classdftefe_1_1quadrature_1_1QuadratureRule.html#af57568a7ed989a5717f3985ccfdf8263',1,'dftefe::quadrature::QuadratureRule::QuadratureRule()']]],
  ['quadratureruleadaptive_2',['QuadratureRuleAdaptive',['../classdftefe_1_1quadrature_1_1QuadratureRuleAdaptive.html#a45e26bbb7bb431ba03bd65cd4428d9f6',1,'dftefe::quadrature::QuadratureRuleAdaptive']]],
  ['quadratureruleattributes_3',['QuadratureRuleAttributes',['../classdftefe_1_1quadrature_1_1QuadratureRuleAttributes.html#a1db39c81fa7f661acb6a1cdc8ed97562',1,'dftefe::quadrature::QuadratureRuleAttributes::QuadratureRuleAttributes()'],['../classdftefe_1_1quadrature_1_1QuadratureRuleAttributes.html#a153eb14b261020b5a87fcba2040e1402',1,'dftefe::quadrature::QuadratureRuleAttributes::QuadratureRuleAttributes(const QuadratureFamily quadratureFamily, const bool isCartesianTensorStructured, const size_type num1DPoints=0)']]],
  ['quadraturerulecontainer_4',['QuadratureRuleContainer',['../classdftefe_1_1quadrature_1_1QuadratureRuleContainer.html#a6e9cfbdc335fa04022b78f843c5b05a7',1,'dftefe::quadrature::QuadratureRuleContainer::QuadratureRuleContainer(const QuadratureRuleAttributes &amp;quadratureRuleAttributes, std::shared_ptr&lt; const QuadratureRule &gt; quadratureRule, std::shared_ptr&lt; const basis::TriangulationBase &gt; triangulation, const basis::CellMappingBase &amp;cellMapping)'],['../classdftefe_1_1quadrature_1_1QuadratureRuleContainer.html#aa6c0f3551d1fdffeb25464d2eec78526',1,'dftefe::quadrature::QuadratureRuleContainer::QuadratureRuleContainer(const QuadratureRuleAttributes &amp;quadratureRuleAttributes, std::vector&lt; std::shared_ptr&lt; const QuadratureRule &gt; &gt; quadratureRuleVec, std::shared_ptr&lt; const basis::TriangulationBase &gt; triangulation, const basis::CellMappingBase &amp;cellMapping)'],['../classdftefe_1_1quadrature_1_1QuadratureRuleContainer.html#a0fe03e85b96e08c3942dcbc819d40aad',1,'dftefe::quadrature::QuadratureRuleContainer::QuadratureRuleContainer(const QuadratureRuleAttributes &amp;quadratureRuleAttributes, std::shared_ptr&lt; const QuadratureRule &gt; baseQuadratureRule, std::shared_ptr&lt; const basis::TriangulationBase &gt; triangulation, const basis::CellMappingBase &amp;cellMapping, basis::ParentToChildCellsManagerBase &amp;parentToChildCellsManager, std::vector&lt; std::shared_ptr&lt; const utils::ScalarSpatialFunctionReal &gt; &gt; functions, const std::vector&lt; double &gt; &amp;tolerances, const std::vector&lt; double &gt; &amp;integralThresholds, const double smallestCellVolume=1e-12, const unsigned int maxRecursion=100)']]],
  ['quadraturerulegauss_5',['QuadratureRuleGauss',['../classdftefe_1_1quadrature_1_1QuadratureRuleGauss.html#aa3ed6dc18caa47bc0635dec0d2219551',1,'dftefe::quadrature::QuadratureRuleGauss']]],
  ['quadraturerulegll_6',['QuadratureRuleGLL',['../classdftefe_1_1quadrature_1_1QuadratureRuleGLL.html#a1cf922ffde7d591c33c8eef7196ebb50',1,'dftefe::quadrature::QuadratureRuleGLL']]],
  ['quadraturevaluescontainer_7',['QuadratureValuesContainer',['../classdftefe_1_1quadrature_1_1QuadratureValuesContainer.html#aefb80103008c1236ddb2f6c7ca43a291',1,'dftefe::quadrature::QuadratureValuesContainer::QuadratureValuesContainer()'],['../classdftefe_1_1quadrature_1_1QuadratureValuesContainer.html#aef121dfd8d51b31ef8a73f2b45e5a524',1,'dftefe::quadrature::QuadratureValuesContainer::QuadratureValuesContainer(const QuadratureRuleContainer &amp;quadratureRuleContainer, const size_type numberComponents, const ValueType initVal=ValueType())'],['../classdftefe_1_1quadrature_1_1QuadratureValuesContainer.html#a336989f5061834c9963eb0ee20f68e5f',1,'dftefe::quadrature::QuadratureValuesContainer::QuadratureValuesContainer(const QuadratureValuesContainer &amp;u)'],['../classdftefe_1_1quadrature_1_1QuadratureValuesContainer.html#aa06c606f3913e4487289777535e2392b',1,'dftefe::quadrature::QuadratureValuesContainer::QuadratureValuesContainer(QuadratureValuesContainer &amp;&amp;u)']]]
];
